name: CI with AWS SES Email

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build (example)
        run: |
          echo "Simulating build..."
          # To test failure, uncomment:
          # exit 1

      - name: Send Email Notification (on success)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SES_SMTP_ENDPOINT }}
          server_port: ${{ secrets.SES_SMTP_PORT }}
          username: ${{ secrets.SES_SMTP_USERNAME }}
          password: ${{ secrets.SES_SMTP_PASSWORD }}
          subject: ✅ Build Success: ${{ github.repository }}
          body: |
            Build for ${{ github.repository }} on branch `${{ github.ref_name}}` was successful!
            
            Commit: `${{ github.sha}}`
            Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 'your-recipient-email@example.com' # Replace with actual recipient
          from: 'verified-sender@yourdomain.com' # Replace with your SES verified identity

      - name: Send Email Notification (on failure)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SES_SMTP_ENDPOINT }}
          server_port: ${{ secrets.SES_SMTP_PORT }}
          username: ${{ secrets.SES_SMTP_USERNAME }}
          password: ${{ secrets.SES_SMTP_PASSWORD }}
          subject: ❌ Build FAILED: ${{ github.repository }}
          body: |
            *ALERT:* Build for ${{ github.repository }} on branch `${{ github.ref_name}}` *FAILED!*
            
            Commit: `${{ github.sha}}`
            *Please review logs:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: 'your-recipient-email@example.com'
          from: 'verified-sender@yourdomain.com'
